project_id = "oacmuheaobrluhvkwayc"

[functions]
  [functions.admin-users]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.generate-keywords]
    verify_jwt = false
  [functions.refresh-trends]
    verify_jwt = false
  [functions.ensemble-search]
    verify_jwt = false
  [functions.socialkit]
    verify_jwt = false
  [functions.cleanup-broken-covers]
    verify_jwt = false
  [functions.check-broken-covers]
    verify_jwt = false
