project_id = "oacmuheaobrluhvkwayc"

[functions.socialkit]
verify_jwt = false

[functions.refresh-trends]
verify_jwt = false

[functions.generate-keywords]
verify_jwt = false

[functions.admin-users]
verify_jwt = false
